# Getting all arrivals to all stops of a given line in a given day

## Install dependencies

This notebook requires two dependencies which can be installed with the following command `pip install pandas open-bus-stride-client`.

You can also launch it online at [this URL](https://mybinder.org/v2/gh/hasadna/open-bus-stride-client/HEAD?labpath=notebooks%2Fgetting%20all%20arrivals%20to%20all%20stops%20of%20a%20given%20line%20in%20a%20given%20day.ipynb), when launching online the dependencies are already installed.

## Import dependencies

In [1]:
import datetime

from ipywidgets import DatePicker
from IPython.display import display

# we use pandas to visualize the results we get
import pandas as pd

# The stride client library, used to make the calls to the stride api
import stride

## Pick a date

First, we pick the day we want to analyze, GTFS data queries should be limited to a specific date

You can use the date picker to choose a date which will be used in the next code blocks

In [2]:
date_widget = DatePicker(description='Date:', value=datetime.date(2022,1,23))
display(date_widget)

DatePicker(value=datetime.date(2022, 1, 23), description='Date:')

## Get list of GTFS Routes

For this example we get routes based on route_short_name which is usually the route number in the GTFS data

We look for all routes on the given day matchin route_short_name `360`

In [3]:
gtfs_routes = stride.get('/gtfs_routes/list', {
    'date_from': date_widget.value, 'date_to': date_widget.value,
    'route_short_name': 360,
}, pre_requests_callback='print')
pd.DataFrame(gtfs_routes)

https://open-bus-stride-api.hasadna.org.il/gtfs_routes/list?date_from=2022-01-23&date_to=2022-01-23&route_short_name=360

,id,date,line_ref,operator_ref,route_short_name,route_long_name,route_mkt,route_direction,route_alternative,agency_name,route_type
0,47952,2022-01-23,28774,4,360,היכל המשפט/אבא אבן-ירושלים<->סובת התאנה-אפרת-1#,14360,1,#,אגד תעבורה,3
1,47953,2022-01-23,28775,4,360,סובת התאנה-אפרת<->בנייני האומה/שדרות שז''ר-ירו...,14360,2,#,אגד תעבורה,3
2,48116,2022-01-23,29729,4,360,סובת התאנה-אפרת<->בנייני האומה/שדרות שז''ר-ירו...,14360,2,4,אגד תעבורה,3

## Get the line_refs for these routes

The SIRI data uses line_ref to identify routes, so we need to get the line_refs from above data to be used in requests to get the SIRI data

In [4]:
line_refs = [gtfs_route['line_ref'] for gtfs_route in gtfs_routes]
line_refs

[28774, 28775, 29729]

## Get list of SIRI routes

To be able to query the related SIRI data we need to get the SIRI route identifiers

In [5]:
siri_routes = stride.get('/siri_routes/list', {
    'line_refs': ','.join(map(str,line_refs))
}, pre_requests_callback='print')
siri_route_ids = [siri_route['id'] for siri_route in siri_routes]
pd.DataFrame(siri_routes)

https://open-bus-stride-api.hasadna.org.il/siri_routes/list?line_refs=28774%2C28775%2C29729

     id  line_ref  operator_ref
0  2149     28775             4
1  2152     28774             4
2  3624     29729             4

In [6]:
siri_route_ids

[2149, 2152, 3624]

## Get list of SIRI rides

Based on this list of SIRI route identifiers we can get the list of SIRI rides which occured on these routes

We use the scheduled_start_time field which is populated from the SIRI data to limit the rides to the specific date we want to check

This data contains the duration_minutes field which is the duration of the ride from the SIRI data

In [7]:
siri_rides = stride.get('/siri_rides/list', {
    'scheduled_start_time_from': datetime.datetime.combine(date_widget.value, datetime.time(), datetime.timezone.utc),
    'scheduled_start_time_to': datetime.datetime.combine(date_widget.value, datetime.time(23,59), datetime.timezone.utc),
    'siri_route_ids': ','.join(map(str,siri_route_ids)),
    'order_by': 'scheduled_start_time asc'
}, pre_requests_callback='print')
pd.DataFrame(siri_rides)

https://open-bus-stride-api.hasadna.org.il/siri_rides/list?scheduled_start_time_from=2022-01-23T00%3A00%3A00.000000%2B0000&scheduled_start_time_to=2022-01-23T23%3A59%3A00.000000%2B0000&siri_route_ids=2149%2C2152%2C3624&order_by=scheduled_start_time+asc

,id,siri_route_id,journey_ref,scheduled_start_time,vehicle_ref,updated_first_last_vehicle_locations,first_vehicle_location_id,last_vehicle_location_id,updated_duration_minutes,duration_minutes
0,6382847,2149,2022-01-23-57859359,2022-01-23T03:30:00+00:00,7667469,2022-01-23 05:00:19.697697+00:00,338023517,338067615,2022-01-23 10:00:18.128393+00:00,26
1,6385190,2152,2022-01-23-57859219,2022-01-23T04:00:00+00:00,7668469,2022-01-23 05:00:26.469328+00:00,338088396,338177583,2022-01-23 11:00:17.510985+00:00,28
2,6384972,2149,2022-01-23-57859360,2022-01-23T04:00:00+00:00,7605769,2022-01-23 05:00:25.768295+00:00,338080402,338173691,2022-01-23 11:00:16.916187+00:00,30
3,6387369,2149,2022-01-23-57859361,2022-01-23T04:30:00+00:00,7666869,2022-01-23 06:00:29.084018+00:00,338158485,338282361,2022-01-23 11:00:28.005670+00:00,30
4,6391177,2149,2022-01-23-57859362,2022-01-23T05:00:00+00:00,8212085,2022-01-23 06:00:46.333548+00:00,338311065,338517204,2022-01-23 12:00:29.565259+00:00,39
5,6389899,2152,2022-01-23-57859220,2022-01-23T05:00:00+00:00,79180201,2022-01-23 06:00:37.332745+00:00,338259342,338451889,2022-01-23 12:00:26.949197+00:00,39
6,6392526,2149,2022-01-23-57859363,2022-01-23T05:20:00+00:00,7669769,2022-01-23 06:00:51.862676+00:00,338371142,338565248,2022-01-23 12:00:31.744367+00:00,36
7,6394840,2149,2022-01-23-57859364,2022-01-23T05:40:00+00:00,7666469,2022-01-23 07:00:59.912208+00:00,338484508,338732232,2022-01-23 13:00:38.369494+00:00,46
8,6396949,2149,2022-01-23-57859365,2022-01-23T06:00:00+00:00,79180201,2022-01-23 07:01:11.617046+00:00,338582020,338856756,2022-01-23 13:00:54.215476+00:00,51
9,6396663,2152,2022-01-23-57859221,2022-01-23T06:00:00+00:00,8212085,2022-01-23 07:01:10.352078+00:00,338576404,338819606,2022-01-23 13:00:52.922479+00:00,46
10,6399902,2149,2022-01-23-57859366,2022-01-23T06:30:00+00:00,7670369,2022-01-23 08:01:28.522254+00:00,338748875,339031060,2022-01-23 14:00:27.773559+00:00,55
11,6402458,2152,2022-01-23-57859222,2022-01-23T07:00:00+00:00,7669769,2022-01-23 08:01:47.138673+00:00,338897987,339113264,2022-01-23 14:00:39.120558+00:00,45
12,6402457,2149,2022-01-23-57859367,2022-01-23T07:00:00+00:00,7666769,2022-01-23 08:01:47.130745+00:00,338892606,339127688,2022-01-23 14:00:39.116555+00:00,48
13,6407753,2149,2022-01-23-57859368,2022-01-23T08:00:00+00:00,7669769,2022-01-23 09:02:38.257216+00:00,339183348,339376690,2022-01-23 15:00:27.025142+00:00,42
14,6408090,2152,2022-01-23-57859223,2022-01-23T08:00:00+00:00,79180201,2022-01-23 09:02:40.040499+00:00,339197805,339372220,2022-01-23 15:00:27.718722+00:00,39
15,6413005,2149,2022-01-23-57859369,2022-01-23T09:00:00+00:00,7605769,2022-01-23 10:03:32.286835+00:00,339455881,339627001,2022-01-23 16:00:27.140142+00:00,38
16,6413006,2152,2022-01-23-57859224,2022-01-23T09:00:00+00:00,7666769,2022-01-23 10:03:32.289818+00:00,339455882,339622282,2022-01-23 16:00:27.143463+00:00,37
17,6418384,2152,2022-01-23-57859225,2022-01-23T10:00:00+00:00,8212085,2022-01-23 11:03:10.223654+00:00,339729721,339971333,2022-01-23 17:00:29.740916+00:00,50
18,6419019,2149,2022-01-23-57859370,2022-01-23T10:00:00+00:00,79180201,2022-01-23 11:02:15.409195+00:00,339754003,339898488,2022-01-23 17:00:19.239588+00:00,29
19,6424176,2152,2022-01-23-57859226,2022-01-23T11:00:00+00:00,7669969,2022-01-23 12:03:36.807305+00:00,340024283,340226070,2022-01-23 18:00:21.974325+00:00,41
20,6424174,2149,2022-01-23-57859371,2022-01-23T11:00:00+00:00,7666769,2022-01-23 12:03:36.799463+00:00,340019171,340167466,2022-01-23 18:00:21.970286+00:00,30
21,6431212,2149,2022-01-23-57859372,2022-01-23T12:00:00+00:00,7670169,2022-01-23 13:00:07.330671+00:00,340370631,340581728,2022-01-23 19:00:13.485392+00:00,40
22,6430792,2152,2022-01-23-57859227,2022-01-23T12:00:00+00:00,79180201,2022-01-23 13:03:18.181461+00:00,340348527,340635848,2022-01-23 19:00:24.035761+00:00,55
23,6436772,2149,2022-01-23-57859373,2022-01-23T13:00:00+00:00,7669869,2022-01-23 14:03:44.727470+00:00,340651996,340895554,2022-01-23 20:00:18.346304+00:00,44
24,6437100,2152,2022-01-23-57859228,2022-01-23T13:00:00+00:00,8212385,2022-01-23 14:03:12.733568+00:00,340674523,340963654,2022-01-23 20:00:18.660714+00:00,52
25,6443216,2149,2022-01-23-57859374,2022-01-23T14:00:00+00:00,7667569,2022-01-23 15:03:20.432227+00:00,340991723,341292191,2022-01-23 21:00:19.542740+00:00,51
26,6442990,2152,2022-01-23-57859229,2022-01-23T14:00:00+00:00,7670169,2022-01-23 15:03:19.582018+00:00,340991724,341292192,2022-01-23 21:00:19.127625+00:00,52
27,6445906,2152,2022-01-23-57859230,2022-01-23T14:30:00+00:00,7669969,2022-01-23 16:02:50.984317+00:00,341164175,341531562,2022-01-23 22:00:17.579099+00:00,62
28,6449042,2152,2022-01-23-57859231,2022-01-23T15:00:00+00:00,7669869,2022-01-23 16:03:10.421179+00:00,341345474,341685598,2022-01-23 22:00:24.260490+00:00,60
29,6449461,2149,2022-01-23-57859375,2022-01-23T15:00:00+00:00,8212385,2022-01-23 16:03:12.449134+00:00,341357746,341647473,2022-01-23 22:00:09.819696+00:00,50
30,6452441,2149,2022-01-23-57859376,2022-01-23T15:30:00+00:00,7670169,2022-01-23 17:02:51.838373+00:00,341537512,341807870,2022-01-23 23:00:14.161505+00:00,49
31,6452300,2152,2022-01-23-57859232,2022-01-23T15:30:00+00:00,7667569,2022-01-23 17:02:51.368522+00:00,341525572,341889289,2022-01-23 23:00:13.918356+00:00,65
32,6456188,2152,2022-01-23-57859233,2022-01-23T16:00:00+00:00,7669969,2022-01-23 17:03:07.297074+00:00,341758746,342017220,2022-01-23 23:00:20.881419+00:00,50
33,6455329,2149,2022-01-23-57859377,2022-01-23T16:00:00+00:00,79180201,2022-01-23 17:03:06.730782+00:00,341702605,341952155,2022-01-23 23:00:20.330071+00:00,47
34,6457560,2152,2022-01-23-57859234,2022-01-23T16:30:00+00:00,8212185,2022-01-23 18:02:51.886447+00:00,341856494,342142186,2022-01-24 00:00:17.197861+00:00,58
35,6457559,2149,2022-01-23-57859378,2022-01-23T16:30:00+00:00,7669869,2022-01-23 18:02:51.882035+00:00,341850938,342086588,2022-01-24 00:00:17.194735+00:00,46
36,6460769,2152,2022-01-23-57859235,2022-01-23T17:00:00+00:00,7667769,2022-01-23 18:03:08.159297+00:00,342017222,342256986,2022-01-24 00:00:28.193271+00:00,52
37,6463044,2149,2022-01-23-57859379,2022-01-23T17:30:00+00:00,7669969,2022-01-23 19:03:05.124109+00:00,342155805,342318726,2022-01-24 01:00:11.734572+00:00,40
38,6463045,2152,2022-01-23-57859236,2022-01-23T17:30:00+00:00,7670169,2022-01-23 19:03:05.128727+00:00,342151131,342365098,2022-01-24 01:00:11.736578+00:00,52
39,6465739,2152,2022-01-23-57859237,2022-01-23T18:00:00+00:00,79180101,2022-01-23 19:03:17.060775+00:00,342289661,342458759,2022-01-24 01:00:07.359075+00:00,48
40,6467896,2149,2022-01-23-57859380,2022-01-23T18:30:00+00:00,7667769,2022-01-23 19:03:23.196201+00:00,342409256,342497601,2022-01-24 01:00:21.540800+00:00,27
41,6470253,2152,2022-01-23-57859238,2022-01-23T19:00:00+00:00,7670469,2022-01-23 20:01:55.898228+00:00,342521459,342630631,2022-01-24 02:00:15.387621+00:00,38
42,6471963,2149,2022-01-23-57859381,2022-01-23T19:30:00+00:00,79180101,2022-01-23 20:02:35.893729+00:00,342607523,342692678,2022-01-24 03:00:06.967503+00:00,32
43,6473283,2152,2022-01-23-57859239,2022-01-23T20:00:00+00:00,7669869,2022-01-23 21:02:13.186952+00:00,342679130,342756161,2022-01-24 03:00:13.111012+00:00,34
44,6475123,3624,2022-01-23-58928060,2022-01-23T20:30:00+00:00,7669869,2022-01-23 21:02:19.137035+00:00,342761267,342805473,2022-01-24 03:00:15.754134+00:00,22
45,6475832,2152,2022-01-23-57859240,2022-01-23T21:00:00+00:00,7668869,2022-01-23 22:02:06.083802+00:00,342812433,342884114,2022-01-24 04:00:13.230529+00:00,41
46,6476985,3624,2022-01-23-58928059,2022-01-23T21:30:00+00:00,7668169,2022-01-23 22:02:10.213870+00:00,342864952,342905767,2022-01-24 04:00:15.132271+00:00,27
47,6477923,2152,2022-01-24-57859241,2022-01-23T22:00:00+00:00,79180101,2022-01-23 23:02:07.987144+00:00,342912947,342943020,2022-01-24 05:00:11.140788+00:00,30

## Choose a ride

There are usually a lot of rides for a given route, let's choose one of the rides to investigave

In [8]:
siri_ride_id = 6402458

## Get the ride-stops for this ride

Siri ride-stops contain all the list of stops on this ride, the vehicle locations are then related to this ride stop

In [9]:
siri_ride_stops = stride.get('/siri_ride_stops/list', {
    'siri_ride_ids': str(siri_ride_id),
    'order_by': 'order asc'
}, pre_requests_callback='print')
pd.DataFrame(siri_ride_stops)

https://open-bus-stride-api.hasadna.org.il/siri_ride_stops/list?siri_ride_ids=6402458&order_by=order+asc

           id  siri_stop_id  siri_ride_id  order
0   165965976          3375       6402458      1
1   165981643          1592       6402458      2
2   165999999          1600       6402458      3
3   166020333          1172       6402458      4
4   166040442          2984       6402458      5
5   166055311         15955       6402458      7
6   166060155          2519       6402458      8
7   166062550         16305       6402458      9
8   166069856          3227       6402458     10
9   166072174          3228       6402458     11
10  166074404          5253       6402458     12

## Find all vehicle locations along this ride

Now we can get the list of all vehicle locations along these ride-stops

Each vehicle location is related to the siri_ride_stop_id which is closest to this location (according to the MOT SIRI data)

In [13]:
pd.DataFrame(stride.get('/siri_vehicle_locations/list', {
    'siri_ride_stop_ids': ','.join([str(siri_ride_stop['id']) for siri_ride_stop in siri_ride_stops]),
    'order_by': 'recorded_at_time asc'
}, pre_requests_callback='print'))

https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/list?siri_ride_stop_ids=165965976%2C165981643%2C165999999%2C166020333%2C166040442%2C166055311%2C166060155%2C166062550%2C166069856%2C166072174%2C166074404&order_by=recorded_at_time+asc

,id,siri_snapshot_id,siri_ride_stop_id,recorded_at_time,lon,lat,bearing,velocity,distance_from_journey_start
0,338897987,215956,165965976,2022-01-23T06:55:00+00:00,35.206916,31.785791,168,4,0
1,338903336,215957,165965976,2022-01-23T06:55:00+00:00,35.206916,31.785791,168,4,0
2,338908635,215958,165965976,2022-01-23T06:55:00+00:00,35.206916,31.785791,168,4,0
3,338913913,215959,165965976,2022-01-23T06:55:00+00:00,35.206916,31.785791,168,4,0
4,338919242,215960,165965976,2022-01-23T07:00:02+00:00,35.205318,31.786596,282,0,0
5,338924585,215961,165965976,2022-01-23T07:01:15+00:00,35.204048,31.786872,282,0,172
6,338929863,215962,165981643,2022-01-23T07:02:06+00:00,35.203979,31.787174,282,0,216
7,338935061,215963,165981643,2022-01-23T07:03:15+00:00,35.204170,31.787933,6,0,344
8,338940181,215964,165981643,2022-01-23T07:04:29+00:00,35.203632,31.787902,34,0,390
9,338945342,215965,165981643,2022-01-23T07:05:14+00:00,35.202060,31.787563,250,0,555
10,338950491,215966,165981643,2022-01-23T07:05:14+00:00,35.202060,31.787563,250,0,555
11,338955599,215967,165981643,2022-01-23T07:07:14+00:00,35.200340,31.787887,290,0,719
12,338960664,215968,165981643,2022-01-23T07:07:14+00:00,35.200340,31.787887,290,0,719
13,338965662,215969,165999999,2022-01-23T07:09:14+00:00,35.199100,31.786966,290,0,904
14,338970764,215970,165999999,2022-01-23T07:09:14+00:00,35.199100,31.786966,290,0,904
15,338975896,215971,165999999,2022-01-23T07:11:41+00:00,35.195266,31.780288,212,61,1819
16,338980984,215972,165999999,2022-01-23T07:12:34+00:00,35.194763,31.770729,170,68,2917
17,338986010,215973,165999999,2022-01-23T07:13:27+00:00,35.193744,31.761077,166,72,4030
18,338990970,215974,165999999,2022-01-23T07:14:26+00:00,35.190544,31.754114,193,58,4883
19,338996031,215975,165999999,2022-01-23T07:14:26+00:00,35.190544,31.754114,193,58,4883
20,339001119,215976,165999999,2022-01-23T07:16:26+00:00,35.189491,31.753091,226,0,5028
21,339006191,215977,166020333,2022-01-23T07:17:27+00:00,35.188869,31.749624,162,40,5451
22,339011227,215978,166020333,2022-01-23T07:17:27+00:00,35.188869,31.749624,162,40,5451
23,339016214,215979,166020333,2022-01-23T07:19:32+00:00,35.198173,31.743038,134,90,6609
24,339021203,215980,166020333,2022-01-23T07:20:31+00:00,35.202533,31.731922,204,97,8010
25,339026165,215981,166020333,2022-01-23T07:21:38+00:00,35.191650,31.725933,254,65,9309
26,339031063,215982,166020333,2022-01-23T07:22:33+00:00,35.184730,31.721689,210,47,10112
27,339035897,215983,166020333,2022-01-23T07:22:56+00:00,35.181980,31.718713,223,68,10528
28,339040642,215984,166020333,2022-01-23T07:24:37+00:00,35.170799,31.707378,200,47,12258
29,339045618,215985,166040442,2022-01-23T07:25:35+00:00,35.162876,31.706092,281,76,13100
30,339050653,215986,166040442,2022-01-23T07:25:57+00:00,35.158710,31.705091,241,50,13503
31,339055598,215987,166040442,2022-01-23T07:27:50+00:00,35.156108,31.694513,157,72,14784
32,339060553,215988,166040442,2022-01-23T07:28:52+00:00,35.159698,31.686691,220,54,16086
33,339065409,215989,166040442,2022-01-23T07:28:52+00:00,35.159698,31.686691,220,54,16086
34,339070296,215990,166040442,2022-01-23T07:30:36+00:00,35.165313,31.684671,90,61,16785
35,339075175,215991,166055311,2022-01-23T07:31:40+00:00,35.168277,31.679422,218,32,17535
36,339080022,215992,166055311,2022-01-23T07:32:53+00:00,35.164455,31.674173,238,54,18340
37,339084777,215993,166060155,2022-01-23T07:33:41+00:00,35.161819,31.669187,204,18,18974
38,339089458,215994,166062550,2022-01-23T07:34:18+00:00,35.160804,31.667562,218,14,19183
39,339094292,215995,166062550,2022-01-23T07:35:20+00:00,35.162860,31.668399,65,14,19533
40,339099141,215996,166062550,2022-01-23T07:36:32+00:00,35.159999,31.665632,211,29,20197
41,339103907,215997,166069856,2022-01-23T07:37:40+00:00,35.155906,31.663518,200,0,20709
42,339108626,215998,166072174,2022-01-23T07:38:41+00:00,35.153816,31.658346,176,47,21344
43,339113264,215999,166074404,2022-01-23T07:39:49+00:00,35.149982,31.655168,240,40,21906